every 300 seconds:
	send "&7------------------------------------------------" to all players
	send "&7- Enjoying the server?" to all players
	send "" to all players
	send "&7- Make sure to check out the discord for" to all players
	send "&7 updates, announcements, sneak peaks and more!" to all players
	send "" to all players
	send "&7- &9&n/discord &7to join the discord!" to all players
	send "&7------------------------------------------------" to all players