command /armorshop:
	trigger:
		loadArmorShopGUI(player)

function loadArmorShopGUI(p: player):
	set {_gui} to chest inventory with 5 rows named "&6&lArmorer"

	loop 27 times:
		set slot (loop-number - 1) of {_gui} to orange stained glass pane named " "

	open {_gui} to {_p}

on inventory click:
	if event-inventory's name is "&6&lArmorer":
		event-inventory is not player's inventory
		cancel event